### ISSUE TITLE
Extension not activated

### ISSUE THREAD

**Issue by Andre15711** [juju4/ansible-chrome-config#2]
I'm currently testing to configure my Chrome with this role.
In general it is working fine so far. The onyl issue I have with it, that the installed extensions are not activated after the first start of the Chrome browser.
Chrome shows errors in the top right corner (one error per extensio). After activating the extension manualy everything is working fine and the errors disappears.
Any ideas?

Best regards
André

**Comment by juju4** [comment]
What errors do you see?
Which variables configuration are you using? chrome_extensions or chrome_extension_force.
Nowadays, I think only the second applies. probably want to remove the other.

**Comment by juju4** [comment]
Closing old issue with no feedback
